dlist.cabal: add missing OverloadedStrings module to tarball
testsuite on hackage package fails as:

  Preprocessing test suite 'test' for dlist-0.8.0.1...
  [1 of 1] Compiling Main             ( tests/Main.hs, dist/build/test/test-tmp/Main.dyn_o )

  tests/Main.hs:24:1: error:
    Failed to load interface for ‘OverloadedStrings’
    Use -v to see a list of the files searched for.

Change adds OverloadedStrings to .cabal file

Signed-off-by: Sergei Trofimovich <siarheit@google.com>